host = ["127.0.0.1:9092"]

[topic_mappings.sms]
strategy = "round-robin"
group = "sms.group"
[[topic_mappings.sms.topics]]
name = "sms.high"
weight = 100
[[topic_mappings.sms.topics]]
name = "sms.medium"
weight = 100
[[topic_mappings.sms.topics]]
name = "sms.low"
weight = 100

[topic_mappings.email]
strategy = "round-robin"
group = "email.group"
[[topic_mappings.email.topics]]
name = "email.high"
weight = 100
[[topic_mappings.email.topics]]
name = "email.medium"
weight = 100
[[topic_mappings.email.topics]]
name = "email.low"
weight = 100

[topic_mappings.push]
strategy = "round-robin"
group = "push.group"
[[topic_mappings.push.topics]]
name = "push.high"
weight = 100
[[topic_mappings.push.topics]]
name = "push.medium"
weight = 100
[[topic_mappings.push.topics]]
name = "push.low"
weight = 100
